-- Cross-link pass for "Transformation and orchestration" + "Analytics engineering".
-- Run after both new section seeds and the five domain seeds exist. Also restores
-- the two links affected by removing "Analytics engineering practice":
--   data-modeling -> Analytics engineering, semantics -> ML / AI integration.
-- Idempotent.

insert into links (source_type, source_id, target_type, target_id, context)
select 'page', s.id, 'page', t.id, 'wikilink'
from (values
('transformation-and-orchestration', 'Data modeling'),
('transformation-and-orchestration', 'What the transformation layer is'),
('transformation-and-orchestration', 'What orchestration is'),
('transformation-and-orchestration', 'Transformation and orchestration voices and canon'),
('what-the-transformation-layer-is', 'How to structure a dbt project'),
('what-the-transformation-layer-is', 'Materialization strategies'),
('what-the-transformation-layer-is', 'What analytics engineering is'),
('how-to-structure-a-dbt-project', 'Modeling theory'),
('how-to-structure-a-dbt-project', 'Grain'),
('how-to-structure-a-dbt-project', 'What the transformation layer is'),
('how-to-structure-a-dbt-project', 'Modeling approaches in dbt'),
('materialization-strategies', 'Cost as a data product'),
('materialization-strategies', 'How to structure a dbt project'),
('materialization-strategies', 'Testing & data quality'),
('modeling-approaches-in-dbt', 'Modeling theory'),
('modeling-approaches-in-dbt', 'Grain'),
('modeling-approaches-in-dbt', 'How to structure a dbt project'),
('modeling-approaches-in-dbt', 'The semantic layer'),
('testing-and-data-quality', 'CI/CD and DataOps'),
('testing-and-data-quality', 'The MRR waterfall in dbt'),
('testing-and-data-quality', 'Data observability'),
('the-dbt-ecosystem-in-2026', 'What the transformation layer is'),
('the-dbt-ecosystem-in-2026', 'The semantic layer'),
('the-dbt-ecosystem-in-2026', 'The modern data stack'),
('ml-ai-integration', 'Serving data to AI agents'),
('ml-ai-integration', 'Churn modeling in dbt'),
('ml-ai-integration', 'Testing & data quality'),
('what-orchestration-is', 'The orchestration landscape'),
('what-orchestration-is', 'Orchestrating dbt'),
('what-orchestration-is', 'What the transformation layer is'),
('the-orchestration-landscape', 'Orchestrating dbt'),
('the-orchestration-landscape', 'What orchestration is'),
('the-orchestration-landscape', 'CI/CD and DataOps'),
('orchestrating-dbt', 'The orchestration landscape'),
('orchestrating-dbt', 'CI/CD and DataOps'),
('orchestrating-dbt', 'Materialization strategies'),
('ci-cd-and-dataops', 'Testing & data quality'),
('ci-cd-and-dataops', 'Data observability'),
('ci-cd-and-dataops', 'Orchestrating dbt'),
('data-observability', 'Testing & data quality'),
('data-observability', 'Reconciling the metrics layer with the GL'),
('data-observability', 'CI/CD and DataOps'),
('data-observability', 'What orchestration is'),
('analytics-engineering', 'Data modeling'),
('analytics-engineering', 'Product analytics'),
('analytics-engineering', 'Marketing analytics'),
('analytics-engineering', 'Sales analytics'),
('analytics-engineering', 'Customer experience analytics'),
('analytics-engineering', 'Finance analytics'),
('analytics-engineering', 'Operations analytics'),
('analytics-engineering', 'Transformation and orchestration'),
('analytics-engineering', 'Serving data to AI agents'),
('analytics-engineering', 'What analytics engineering is'),
('analytics-engineering', 'Analytics engineering voices and canon'),
('what-analytics-engineering-is', 'Principles of analytics engineering'),
('what-analytics-engineering-is', 'The analytics engineer''s role'),
('what-analytics-engineering-is', 'Transformation and orchestration'),
('the-analytics-engineer-role', 'Org models (hub and spoke)'),
('the-analytics-engineer-role', 'Team and ownership models'),
('the-analytics-engineer-role', 'What analytics engineering is'),
('the-analytics-engineer-role', 'Principles of analytics engineering'),
('principles-of-analytics-engineering', 'AI and the future of analytics engineering'),
('principles-of-analytics-engineering', 'CI/CD and DataOps'),
('principles-of-analytics-engineering', 'Data contracts and trust'),
('the-modern-data-stack', 'The semantic layer'),
('the-modern-data-stack', 'The dbt ecosystem in 2026'),
('the-modern-data-stack', 'What analytics engineering is'),
('the-semantic-layer', 'Semantics & the semantic layer'),
('the-semantic-layer', 'Serving data to AI agents'),
('the-semantic-layer', 'The modern data stack'),
('data-contracts-and-trust', 'Testing & data quality'),
('data-contracts-and-trust', 'Serving data to AI agents'),
('data-contracts-and-trust', 'Principles of analytics engineering'),
('serving-data-to-ai-agents', 'The semantic layer'),
('serving-data-to-ai-agents', 'How taro is built on these ideas'),
('serving-data-to-ai-agents', 'Presentation layers'),
('presentation-layers', 'The semantic layer'),
('presentation-layers', 'How taro is built on these ideas'),
('presentation-layers', 'Serving data to AI agents'),
('ai-and-the-future-of-analytics-engineering', 'Serving data to AI agents'),
('ai-and-the-future-of-analytics-engineering', 'Principles of analytics engineering'),
('ai-and-the-future-of-analytics-engineering', 'Data contracts and trust'),
('how-taro-is-built-on-these-ideas', 'Serving data to AI agents'),
('how-taro-is-built-on-these-ideas', 'Marketing analytics'),
('how-taro-is-built-on-these-ideas', 'Operations analytics'),
('how-taro-is-built-on-these-ideas', 'Data modeling'),
('how-taro-is-built-on-these-ideas', 'Transformation and orchestration'),
('how-taro-is-built-on-these-ideas', 'Semantics & the semantic layer'),
('data-modeling', 'Analytics engineering'),
('semantics-and-the-semantic-layer', 'ML / AI integration')
) e(src_slug, tgt_title)
join pages s on s.slug = e.src_slug
join pages t on lower(t.title) = lower(e.tgt_title)
where s.id <> t.id
on conflict (source_type, source_id, target_type, target_id) do nothing;
