-- Sales analytics wiki section (top-level sibling of "Data modeling").
-- Idempotent: pages upsert by slug; parent wiring and wikilinks are join-based and
-- safe to re-run. Cross-section wikilinks resolve only once the target pages exist,
-- so re-run all five domain seeds after the first pass to wire cross-links.
-- Mirrors what was seeded to the live DB via the Supabase MCP (2026-06).

insert into pages (title, slug, kind, content, visibility) values ('Sales analytics', 'sales-analytics', 'wiki', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Sales analytics answers one question that the whole company cares about: are we going to hit the number. Around it sits pipeline analysis, forecasting, conversion, quota and territory, and the function that owns all of it, RevOps."}]},{"type":"paragraph","content":[{"type":"text","text":"It's the middle of the revenue story. Marketing hands it pipeline, customer success takes the renewal, and sales analytics is the part that tracks deals from opportunity to closed-won and forecasts where they'll land. It sits next to "},{"type":"wikilink","attrs":{"title":"Data modeling"}},{"type":"text","text":" as a domain, and it leans hard on one modeling idea in particular: snapshotting state over time."}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"Theory"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Pipeline — ","marks":[{"type":"bold"}]},{"type":"text","text":"stages and conversion, win rate, sales velocity, pipeline coverage."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Forecasting — ","marks":[{"type":"bold"}]},{"type":"text","text":"commit categories, forecast accuracy, and why the CRM alone is a bad forecast."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Bookings — ","marks":[{"type":"bold"}]},{"type":"text","text":"ACV and ARR, new versus expansion versus renewal, land and expand."}]}]}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"Practice"}]},{"type":"paragraph","content":[{"type":"text","text":"RevOps as a function, CRM hygiene and stage definitions, snapshotting the pipeline, the CRM-warehouse sync, and bookings and ARR modeling in dbt."}]},{"type":"paragraph","content":[{"type":"text","text":"The defining technical challenge is that the CRM only shows you now. Sales analytics is mostly the art of remembering what the pipeline looked like last week, which is a "},{"type":"wikilink","attrs":{"title":"Time in data modeling"}},{"type":"text","text":" problem."}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"The pipeline and stages"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Sales analytics practice"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Sales voices and canon"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('The pipeline and stages', 'the-pipeline-and-stages', 'concept', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The pipeline is the set of open opportunities, each sitting in a stage that represents how far the deal has progressed: discovery, demo, proposal, negotiation, closed. The stages are the backbone of every sales metric, which is why their definitions matter more than they look."}]},{"type":"paragraph","content":[{"type":"text","text":"Stage conversion, the rate at which deals move from one stage to the next, tells you where the pipeline leaks. The catch is that a stage is only meaningful if everyone agrees what it means, and reps are optimistic, so stages drift toward wishful thinking unless they have exit criteria. A deal is in proposal when a proposal was sent, not when a rep feels good about it."}]},{"type":"paragraph","content":[{"type":"text","text":"This picks up where marketing leaves off: an opportunity is the handoff from "},{"type":"wikilink","attrs":{"title":"The acquisition funnel"}},{"type":"text","text":". Modeled well, the pipeline is an "},{"type":"wikilink","attrs":{"title":"Entities, instances & identifiers"}},{"type":"text","text":" problem (account, contact, opportunity, activity) at a clear "},{"type":"wikilink","attrs":{"title":"Grain"}},{"type":"text","text":", and the stage definitions are the contract that keeps it honest. See "},{"type":"wikilink","attrs":{"title":"CRM hygiene and stage definitions"}},{"type":"text","text":"."}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"Win rate and conversion"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"CRM hygiene and stage definitions"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"The acquisition funnel"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('Win rate and conversion', 'win-rate-and-conversion', 'concept', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Win rate is the share of opportunities that become customers. Simple to say, and full of quiet definitional choices: win rate over all opportunities, or only closed ones; counted by deal or by dollar; measured in the cohort that opened or the cohort that closed."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Opportunity win rate — ","marks":[{"type":"bold"}]},{"type":"text","text":"won ÷ (won + lost). The headline number, and the one most affected by which definition you pick."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Stage conversion — ","marks":[{"type":"bold"}]},{"type":"text","text":"the per-stage rate, which localizes where deals die."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"By segment — ","marks":[{"type":"bold"}]},{"type":"text","text":"win rate by source, segment, and rep, because a blended number hides the channel or motion that's actually broken."}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Win rates around 20 to 30% are typical for B2B SaaS (directional); the number matters less than its trend and its breakdown. The modeling subtlety is the cohorting: a win rate measured on deals that closed this quarter mixes in deals that opened long ago, so be explicit about whether you're cohorting by open date or close date. It's a "},{"type":"wikilink","attrs":{"title":"Counting & aggregation"}},{"type":"text","text":" decision dressed as a sales metric."}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"The pipeline and stages"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Sales velocity"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Counting & aggregation"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('Sales velocity', 'sales-velocity', 'concept', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Sales velocity is how fast revenue moves through the pipeline, and it's a useful single number because it combines the four levers you can actually pull:"}]},{"type":"paragraph","content":[{"type":"text","text":"Sales velocity = (number of opportunities × average deal value × win rate) ÷ sales cycle length.","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"type":"text","text":"The formula is a teaching tool as much as a metric. It says there are exactly four ways to grow faster: more deals, bigger deals, a higher win rate, or a shorter cycle. Every sales initiative is really a bet on one of those four terms, and velocity makes the tradeoff visible. Speeding up the cycle by chasing only small deals can lower velocity even though it feels faster."}]},{"type":"paragraph","content":[{"type":"text","text":"Median B2B SaaS sales cycles run around 80 days (directional, varies widely by deal size). For modeling, the trap is the denominator: cycle length is only knowable for closed deals, and averaging it naively biases toward fast deals that closed and ignores slow ones still open. Compute it carefully, on a consistent cohort."}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"Win rate and conversion"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Pipeline coverage"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Sales forecasting"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('Sales forecasting', 'sales-forecasting', 'concept', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Forecasting is the prediction of how much will close in a period, and it's the highest-stakes number sales produces. The naive version, sum the pipeline weighted by stage probability, is also the least accurate, because stage probabilities are averages and every deal thinks it's above average."}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"How it's actually done"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Commit categories — ","marks":[{"type":"bold"}]},{"type":"text","text":"reps and managers tag deals as commit, best case, or pipeline, a judgment layer on top of the raw stages."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Weighted pipeline — ","marks":[{"type":"bold"}]},{"type":"text","text":"expected value by stage probability. A baseline, not a forecast."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Revenue intelligence — ","marks":[{"type":"bold"}]},{"type":"text","text":"tools like Clari and Gong add signals (deal activity, conversation data) the CRM doesn't capture, and track forecast bias by manager over time."}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"The insight that justifies the whole revenue-intelligence category: the CRM shows what reps typed, not what's happening, so a forecast built only on CRM stages inherits every optimistic field. The analytics-engineering contribution is forecast accuracy tracking, comparing each week's forecast to what actually landed, which requires remembering the forecast, which requires "},{"type":"wikilink","attrs":{"title":"Snapshotting the pipeline"}},{"type":"text","text":"."}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"Pipeline coverage"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Snapshotting the pipeline"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Sales velocity"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('Pipeline coverage', 'pipeline-coverage', 'concept', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Pipeline coverage is the ratio of open qualified pipeline to the revenue target for the period. It answers a planning question: do we even have enough deals in flight to hit the number, before we worry about whether they'll close."}]},{"type":"paragraph","content":[{"type":"text","text":"Coverage = total qualified pipeline ÷ revenue target.","marks":[{"type":"bold"}]}]},{"type":"paragraph","content":[{"type":"text","text":"The rule of thumb is 3x as a floor, 4x to 5x as comfortable, because not every deal closes and the target needs a cushion. The right multiple is just the inverse of your win rate with a margin, so a team with a low win rate needs more coverage to hit the same number. A 3x ratio with a 33% win rate is barely break-even on paper."}]},{"type":"paragraph","content":[{"type":"text","text":"For modeling, coverage is a snapshot metric: it's the pipeline as it stood on a date against the target, so it only means something if you can reconstruct the pipeline at that date. Tracking coverage over the quarter, watching it build or erode, is more useful than any single reading, and that history again depends on "},{"type":"wikilink","attrs":{"title":"Snapshotting the pipeline"}},{"type":"text","text":"."}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"Sales velocity"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Sales forecasting"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Snapshotting the pipeline"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('Bookings, ACV and ARR', 'bookings-acv-and-arr', 'concept', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Sales closes bookings; finance turns them into recurring revenue. The terms overlap enough to cause trouble, so pin them down."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Bookings — ","marks":[{"type":"bold"}]},{"type":"text","text":"the total value of a signed contract, including future periods. What sales is measured on."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"ACV — ","marks":[{"type":"bold"}]},{"type":"text","text":"annual contract value, the contract normalized to a year, excluding one-time fees."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"ARR — ","marks":[{"type":"bold"}]},{"type":"text","text":"annual recurring revenue, the recurring portion annualized. The number the board tracks."}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"A three-year deal has a big total contract value, a smaller ACV, and an ARR equal to its yearly recurring rate. Reporting the wrong one inflates or deflates the story, and a deal signed is not yet revenue recognized. The full distinction lives on the finance side at "},{"type":"wikilink","attrs":{"title":"Bookings, billings, revenue, cash"}},{"type":"text","text":" and "},{"type":"wikilink","attrs":{"title":"MRR and ARR"}},{"type":"text","text":"."}]},{"type":"paragraph","content":[{"type":"text","text":"The handoff between sales bookings and finance ARR is a classic reconciliation seam, and it's where the CRM and the billing system have to agree. They rarely do without a model in between."}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"New, expansion and renewal bookings"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Bookings, billings, revenue, cash"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"MRR and ARR"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('New, expansion and renewal bookings', 'new-expansion-renewal-bookings', 'concept', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Not all bookings are equal, and splitting them is where sales analytics meets the SaaS growth story."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"New — ","marks":[{"type":"bold"}]},{"type":"text","text":"first contract with a new logo. The hardest and most expensive to win."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Expansion — ","marks":[{"type":"bold"}]},{"type":"text","text":"an existing customer buying more: more seats, a higher tier, a new product. Cheaper than new and the engine of efficient growth."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Renewal — ","marks":[{"type":"bold"}]},{"type":"text","text":"an existing customer continuing. Quiet, essential, and the base everything else builds on."}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"The mix matters more than the total. A company growing on expansion and renewal is healthier than one running flat out on new logos to replace churn, even at the same bookings number. This split is what feeds net revenue retention, and it's why expansion bookings get tracked as carefully as new. See "},{"type":"wikilink","attrs":{"title":"Revenue retention (GRR and NRR)"}},{"type":"text","text":" for the revenue view and "},{"type":"wikilink","attrs":{"title":"Land and expand"}},{"type":"text","text":" for the motion."}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"Bookings, ACV and ARR"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Land and expand"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Revenue retention (GRR and NRR)"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('Land and expand', 'land-and-expand', 'concept', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Land and expand is the motion behind most efficient SaaS growth: win a small initial deal, prove value, then grow the account over time through more seats, tiers, and products. The first deal is a foothold, not the prize."}]},{"type":"paragraph","content":[{"type":"text","text":"It reframes what sales analytics measures. Win rate on the land matters, but the real return shows up in the expansion that follows, which means you have to track an account's trajectory, not just its first contract. Net revenue retention above 100% is land-and-expand working: the existing base grows faster than it churns."}]},{"type":"paragraph","content":[{"type":"text","text":"Sales-led and product-led versions of this look different. Sales-led expansion runs through account managers and QBRs; product-led expansion runs through usage crossing a threshold, surfaced as a product-qualified account. Either way the analytics challenge is the same: connect the first deal to everything that came after, which is an account-grain, time-aware modeling problem and a direct tie to "},{"type":"wikilink","attrs":{"title":"Customer success analytics"}},{"type":"text","text":"."}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"New, expansion and renewal bookings"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Customer success analytics"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Revenue retention (GRR and NRR)"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('Sales voices and canon', 'sales-voices-and-canon', 'wiki', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Sales analytics and RevOps lean heavily on vendor-led thought leadership and a strong practitioner community. Who to read and why."}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"The platforms as publishers"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Clari — ","marks":[{"type":"bold"}]},{"type":"text","text":"the forecasting and pipeline-intelligence canon: commit categories, forecast accuracy, pipeline inspection."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Gong — ","marks":[{"type":"bold"}]},{"type":"text","text":"revenue intelligence and the argument that conversation data beats CRM-stage data for forecasting."}]}]}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"RevOps and frameworks"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"The RevOps community — ","marks":[{"type":"bold"}]},{"type":"text","text":"Pavilion, RevGenius, and the broader RevOps movement that reframed sales ops as a cross-functional function."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Gartner — ","marks":[{"type":"bold"}]},{"type":"text","text":"the revenue-operations research and maturity framing."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Winning by Design — ","marks":[{"type":"bold"}]},{"type":"text","text":"the bowtie and recurring-revenue process frameworks widely used to model the funnel past the sale."}]}]}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"Note on benchmarks"}]},{"type":"paragraph","content":[{"type":"text","text":"Win rates, cycle lengths, and coverage ratios cited here are directional industry figures with wide variance by segment and deal size. Use the trend, not the absolute."}]},{"type":"paragraph","content":[{"type":"text","text":"Like marketing, this domain has more influential blogs and communities than canonical books. There's no single Kimball of sales analytics.","marks":[{"type":"italic"}]}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('Sales analytics practice', 'sales-analytics-practice', 'wiki', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The theory is the metrics. This hub is the build, and it's dominated by two problems: the CRM is messy, and the CRM only shows the present."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"RevOps as the function that owns the data."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"CRM hygiene and stage definitions, the quality floor for everything."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Snapshotting the pipeline over time, the defining technical move."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"The CRM-warehouse sync and reverse ETL, and bookings and ARR modeling in dbt."}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"Sales analytics"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Snapshotting the pipeline"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('RevOps as a function', 'revops-as-a-function', 'concept', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Revenue operations is the function that unifies sales, marketing, and customer success operations under one team, around the full customer lifecycle. It exists because those three ran as silos with their own tools, definitions, and numbers, and the seams between them leaked revenue."}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"What RevOps owns"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Process — ","marks":[{"type":"bold"}]},{"type":"text","text":"how a deal flows from first touch to closed-won to renewal, standardized."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Systems — ","marks":[{"type":"bold"}]},{"type":"text","text":"the revenue tech stack, CRM through CS platform, integrated so data flows between them."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Data — ","marks":[{"type":"bold"}]},{"type":"text","text":"a single source of truth for revenue: field definitions, dedup rules, hygiene."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Analytics — ","marks":[{"type":"bold"}]},{"type":"text","text":"the forecast, the pipeline review, the board numbers, all sourced from RevOps-owned systems."}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"For analytics engineering, RevOps is the natural partner and sometimes the natural home: data quality, definitions, and attribution are RevOps problems first. The relationship that works is RevOps owning the domain logic and the central data team owning the platform and the conformed models, the same hub-and-spoke split that shows up in "},{"type":"wikilink","attrs":{"title":"Org models (hub and spoke)"}},{"type":"text","text":" and "},{"type":"wikilink","attrs":{"title":"Team and ownership models"}},{"type":"text","text":"."}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"CRM hygiene and stage definitions"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"The MQL dispute"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Team and ownership models"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('CRM hygiene and stage definitions', 'crm-hygiene-and-stage-definitions', 'concept', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Every sales number is downstream of the CRM, and the CRM is filled in by busy, optimistic humans. So CRM hygiene is the quality floor: duplicate accounts, blank close dates, deals parked in a stage they exited months ago, and the metrics built on top inherit all of it."}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"The two fights worth having"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Stage exit criteria — ","marks":[{"type":"bold"}]},{"type":"text","text":"every stage needs an objective definition of what must be true to be in it. Proposal means a proposal was sent. Without criteria, stages become mood rings and conversion rates are fiction."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Required fields at the right moment — ","marks":[{"type":"bold"}]},{"type":"text","text":"force the close date and amount when a deal is created, not at quarter end, or the snapshot history is built on guesses."}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"This is "},{"type":"wikilink","attrs":{"title":"Testing & data quality"}},{"type":"text","text":" pointed at the CRM. Test for deals with impossible dates, stages without amounts, and accounts without owners, and surface them back to the reps who can fix them. The deeper point: you cannot model your way around a CRM nobody maintains, so the hygiene work is part of the analytics job, not someone else's problem."}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"The pipeline and stages"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"RevOps as a function"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Testing & data quality"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('Snapshotting the pipeline', 'snapshotting-the-pipeline', 'concept', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"This is the defining technical move of sales analytics. The CRM is a live system: it shows you the pipeline as it is right now, and it overwrites history as deals change. But almost every interesting sales question is about change over time, so you have to remember the past yourself."}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"How"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Daily snapshots — ","marks":[{"type":"bold"}]},{"type":"text","text":"capture the full state of every open opportunity every day, so you can reconstruct the pipeline as of any date. Storage is cheap; lost history is not."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Slowly changing dimensions — ","marks":[{"type":"bold"}]},{"type":"text","text":"the dimensional-modeling version, type 2, keeping a row per version of a record with valid-from and valid-to dates."}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"With snapshots you can finally answer the real questions: how much pipeline was created last week, which deals slipped a quarter, what the forecast looked like a month ago versus how it landed. Without them, every one of those is unanswerable, because the CRM already overwrote the evidence. This is "},{"type":"wikilink","attrs":{"title":"Time in data modeling"}},{"type":"text","text":" in its most concrete form, and it's why sales analytics is a modeling discipline and not just a dashboard."}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"Sales forecasting"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Time in data modeling"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Bookings and ARR modeling in dbt"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('CRM and warehouse sync', 'crm-and-warehouse-sync', 'concept', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Sales data gets into the warehouse through a connector (Fivetran, Airbyte) that syncs the CRM, Salesforce or HubSpot, into raw tables, usually on a schedule of a few hours. From there dbt stages and models it into the pipeline, snapshot, and bookings tables the metrics read."}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"Two directions, two purposes"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"CRM to warehouse — ","marks":[{"type":"bold"}]},{"type":"text","text":"extract and load for analysis. The standard inbound path, plus daily snapshots layered on top to preserve history."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Warehouse to CRM (reverse ETL) — ","marks":[{"type":"bold"}]},{"type":"text","text":"push modeled fields, a health score, a product-qualified-account flag, an account tier, back into the CRM so reps see them where they work. Tools like Hightouch and Census."}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Reverse ETL is what closes the loop: the warehouse computes something the CRM can't, and pushes it back to the point of action. It's the same activation pattern marketing uses, and it makes the warehouse the brain and the CRM the interface. The reconciliation challenge underneath is real: CRM bookings and billing-system revenue have to be tied together, which is the subject of "},{"type":"wikilink","attrs":{"title":"Bookings and ARR modeling in dbt"}},{"type":"text","text":"."}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"Snapshotting the pipeline"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"Bookings and ARR modeling in dbt"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"The marketing data stack"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
insert into pages (title, slug, kind, content, visibility) values ('Bookings and ARR modeling in dbt', 'bookings-and-arr-modeling-in-dbt', 'concept', $j${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Turning closed deals into a clean bookings and ARR model is where sales and finance analytics meet, and where their two systems have to be reconciled. The CRM knows what was sold; the billing system knows what's being charged; they disagree, and the model is the referee."}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"The shape"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Opportunity to booking — ","marks":[{"type":"bold"}]},{"type":"text","text":"model won opportunities into bookings, split into new, expansion, and renewal by comparing each account's history."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Booking to ARR — ","marks":[{"type":"bold"}]},{"type":"text","text":"normalize contract values to recurring annual amounts, the bridge from the sales number to the finance number."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Reconcile to billing — ","marks":[{"type":"bold"}]},{"type":"text","text":"tie CRM bookings to billing-system subscriptions, and flag the gaps as data quality, not mystery."}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"The new-versus-expansion split is the same classification logic as the "},{"type":"wikilink","attrs":{"title":"The MRR waterfall in dbt"}},{"type":"text","text":", just sourced from the CRM instead of the billing system, which is exactly why the two have to agree. Define the bookings categories once and reuse them on both sides. This is the sales contribution to the single ARR number the whole company quotes."}]},{"type":"paragraph","content":[{"type":"text","text":"Related: ","marks":[{"type":"bold"}]},{"type":"wikilink","attrs":{"title":"Bookings, ACV and ARR"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"The MRR waterfall in dbt"}},{"type":"text","text":" · "},{"type":"wikilink","attrs":{"title":"A single source of truth for ARR"}}]}]}$j$::jsonb, 'viewer') on conflict (slug) do nothing;
update pages c set parent_id = pa.id from pages pa where pa.slug = 'sales-analytics' and c.slug in ('the-pipeline-and-stages','win-rate-and-conversion','sales-velocity','sales-forecasting','pipeline-coverage','bookings-acv-and-arr','new-expansion-renewal-bookings','land-and-expand','sales-voices-and-canon','sales-analytics-practice');
update pages c set parent_id = pa.id from pages pa where pa.slug = 'sales-analytics-practice' and c.slug in ('revops-as-a-function','crm-hygiene-and-stage-definitions','snapshotting-the-pipeline','crm-and-warehouse-sync','bookings-and-arr-modeling-in-dbt');
insert into links (source_type, source_id, target_type, target_id, context)
select 'page', s.id, 'page', t.id, 'wikilink'
from (values
('sales-analytics', 'Data modeling'),
('sales-analytics', 'Time in data modeling'),
('sales-analytics', 'The pipeline and stages'),
('sales-analytics', 'Sales analytics practice'),
('sales-analytics', 'Sales voices and canon'),
('the-pipeline-and-stages', 'The acquisition funnel'),
('the-pipeline-and-stages', 'Entities, instances & identifiers'),
('the-pipeline-and-stages', 'Grain'),
('the-pipeline-and-stages', 'CRM hygiene and stage definitions'),
('the-pipeline-and-stages', 'Win rate and conversion'),
('win-rate-and-conversion', 'Counting & aggregation'),
('win-rate-and-conversion', 'The pipeline and stages'),
('win-rate-and-conversion', 'Sales velocity'),
('sales-velocity', 'Win rate and conversion'),
('sales-velocity', 'Pipeline coverage'),
('sales-velocity', 'Sales forecasting'),
('sales-forecasting', 'Snapshotting the pipeline'),
('sales-forecasting', 'Pipeline coverage'),
('sales-forecasting', 'Sales velocity'),
('pipeline-coverage', 'Snapshotting the pipeline'),
('pipeline-coverage', 'Sales velocity'),
('pipeline-coverage', 'Sales forecasting'),
('bookings-acv-and-arr', 'Bookings, billings, revenue, cash'),
('bookings-acv-and-arr', 'MRR and ARR'),
('bookings-acv-and-arr', 'New, expansion and renewal bookings'),
('new-expansion-renewal-bookings', 'Revenue retention (GRR and NRR)'),
('new-expansion-renewal-bookings', 'Land and expand'),
('new-expansion-renewal-bookings', 'Bookings, ACV and ARR'),
('land-and-expand', 'Customer success analytics'),
('land-and-expand', 'New, expansion and renewal bookings'),
('land-and-expand', 'Revenue retention (GRR and NRR)'),
('sales-analytics-practice', 'Sales analytics'),
('sales-analytics-practice', 'Snapshotting the pipeline'),
('revops-as-a-function', 'Org models (hub and spoke)'),
('revops-as-a-function', 'Team and ownership models'),
('revops-as-a-function', 'CRM hygiene and stage definitions'),
('revops-as-a-function', 'The MQL dispute'),
('crm-hygiene-and-stage-definitions', 'Testing & data quality'),
('crm-hygiene-and-stage-definitions', 'The pipeline and stages'),
('crm-hygiene-and-stage-definitions', 'RevOps as a function'),
('snapshotting-the-pipeline', 'Time in data modeling'),
('snapshotting-the-pipeline', 'Sales forecasting'),
('snapshotting-the-pipeline', 'Bookings and ARR modeling in dbt'),
('crm-and-warehouse-sync', 'Bookings and ARR modeling in dbt'),
('crm-and-warehouse-sync', 'Snapshotting the pipeline'),
('crm-and-warehouse-sync', 'The marketing data stack'),
('bookings-and-arr-modeling-in-dbt', 'The MRR waterfall in dbt'),
('bookings-and-arr-modeling-in-dbt', 'Bookings, ACV and ARR'),
('bookings-and-arr-modeling-in-dbt', 'A single source of truth for ARR')
) e(src_slug, tgt_title)
join pages s on s.slug = e.src_slug
join pages t on lower(t.title) = lower(e.tgt_title)
where s.id <> t.id
on conflict (source_type, source_id, target_type, target_id) do nothing;
