-- Cross-section wikilink pass for the five domain-analytics sections.
-- Run after seed_{marketing,sales,cx,finance,ops}_analytics.sql so every target
-- page exists and all wikilinks (including cross-section) resolve. Idempotent.

insert into links (source_type, source_id, target_type, target_id, context)
select 'page', s.id, 'page', t.id, 'wikilink'
from (values
('marketing-analytics', 'Data modeling'),
('marketing-analytics', 'Product analytics'),
('marketing-analytics', 'The acquisition funnel'),
('marketing-analytics', 'Marketing analytics practice'),
('marketing-analytics', 'Marketing voices and canon'),
('the-acquisition-funnel', 'Grain'),
('the-acquisition-funnel', 'The pipeline and stages'),
('the-acquisition-funnel', 'Attribution models'),
('the-acquisition-funnel', 'Unit economics of acquisition'),
('attribution-models', 'Attribution modeling in dbt'),
('attribution-models', 'Beyond last-touch (MMM and incrementality)'),
('attribution-models', 'The acquisition funnel'),
('beyond-last-touch', 'Experimentation'),
('beyond-last-touch', 'Attribution models'),
('beyond-last-touch', 'Channels and campaign performance'),
('channels-and-campaign-performance', 'Attribution models'),
('channels-and-campaign-performance', 'Unit economics of acquisition'),
('channels-and-campaign-performance', 'The marketing data stack'),
('unit-economics-of-acquisition', 'Unit economics (CAC, LTV, payback)'),
('unit-economics-of-acquisition', 'Channels and campaign performance'),
('unit-economics-of-acquisition', 'Marketing-sourced vs influenced pipeline'),
('sourced-vs-influenced-pipeline', 'The pipeline and stages'),
('sourced-vs-influenced-pipeline', 'The acquisition funnel'),
('sourced-vs-influenced-pipeline', 'Attribution modeling in dbt'),
('the-dark-funnel', 'Attribution models'),
('the-dark-funnel', 'Beyond last-touch (MMM and incrementality)'),
('the-dark-funnel', 'Marketing voices and canon'),
('product-led-acquisition', 'Product analytics'),
('product-led-acquisition', 'Subscription and billing mechanics'),
('product-led-acquisition', 'Metrics that matter'),
('product-led-acquisition', 'The acquisition funnel'),
('marketing-analytics-practice', 'Marketing analytics'),
('marketing-analytics-practice', 'Attribution modeling in dbt'),
('utm-and-tracking-hygiene', 'Testing & data quality'),
('utm-and-tracking-hygiene', 'Identity resolution for marketing'),
('utm-and-tracking-hygiene', 'The marketing data stack'),
('identity-resolution-for-marketing', 'Identity and sessions'),
('identity-resolution-for-marketing', 'Entities, instances & identifiers'),
('identity-resolution-for-marketing', 'Attribution modeling in dbt'),
('attribution-modeling-in-dbt', 'Attribution models'),
('attribution-modeling-in-dbt', 'Identity resolution for marketing'),
('attribution-modeling-in-dbt', 'Semantics & the semantic layer'),
('the-mql-dispute', 'The acquisition funnel'),
('the-mql-dispute', 'Marketing-sourced vs influenced pipeline'),
('the-mql-dispute', 'RevOps as a function'),
('the-marketing-data-stack', 'The platform landscape'),
('the-marketing-data-stack', 'Attribution modeling in dbt'),
('the-marketing-data-stack', 'Materialization strategies'),
('sales-analytics', 'Data modeling'),
('sales-analytics', 'Time in data modeling'),
('sales-analytics', 'The pipeline and stages'),
('sales-analytics', 'Sales analytics practice'),
('sales-analytics', 'Sales voices and canon'),
('the-pipeline-and-stages', 'The acquisition funnel'),
('the-pipeline-and-stages', 'Entities, instances & identifiers'),
('the-pipeline-and-stages', 'Grain'),
('the-pipeline-and-stages', 'CRM hygiene and stage definitions'),
('the-pipeline-and-stages', 'Win rate and conversion'),
('win-rate-and-conversion', 'Counting & aggregation'),
('win-rate-and-conversion', 'The pipeline and stages'),
('win-rate-and-conversion', 'Sales velocity'),
('sales-velocity', 'Win rate and conversion'),
('sales-velocity', 'Pipeline coverage'),
('sales-velocity', 'Sales forecasting'),
('sales-forecasting', 'Snapshotting the pipeline'),
('sales-forecasting', 'Pipeline coverage'),
('sales-forecasting', 'Sales velocity'),
('pipeline-coverage', 'Snapshotting the pipeline'),
('pipeline-coverage', 'Sales velocity'),
('pipeline-coverage', 'Sales forecasting'),
('bookings-acv-and-arr', 'Bookings, billings, revenue, cash'),
('bookings-acv-and-arr', 'MRR and ARR'),
('bookings-acv-and-arr', 'New, expansion and renewal bookings'),
('new-expansion-renewal-bookings', 'Revenue retention (GRR and NRR)'),
('new-expansion-renewal-bookings', 'Land and expand'),
('new-expansion-renewal-bookings', 'Bookings, ACV and ARR'),
('land-and-expand', 'Customer success analytics'),
('land-and-expand', 'New, expansion and renewal bookings'),
('land-and-expand', 'Revenue retention (GRR and NRR)'),
('sales-analytics-practice', 'Sales analytics'),
('sales-analytics-practice', 'Snapshotting the pipeline'),
('revops-as-a-function', 'Org models (hub and spoke)'),
('revops-as-a-function', 'Team and ownership models'),
('revops-as-a-function', 'CRM hygiene and stage definitions'),
('revops-as-a-function', 'The MQL dispute'),
('crm-hygiene-and-stage-definitions', 'Testing & data quality'),
('crm-hygiene-and-stage-definitions', 'The pipeline and stages'),
('crm-hygiene-and-stage-definitions', 'RevOps as a function'),
('snapshotting-the-pipeline', 'Time in data modeling'),
('snapshotting-the-pipeline', 'Sales forecasting'),
('snapshotting-the-pipeline', 'Bookings and ARR modeling in dbt'),
('crm-and-warehouse-sync', 'Bookings and ARR modeling in dbt'),
('crm-and-warehouse-sync', 'Snapshotting the pipeline'),
('crm-and-warehouse-sync', 'The marketing data stack'),
('bookings-and-arr-modeling-in-dbt', 'The MRR waterfall in dbt'),
('bookings-and-arr-modeling-in-dbt', 'Bookings, ACV and ARR'),
('bookings-and-arr-modeling-in-dbt', 'A single source of truth for ARR'),
('cx-analytics', 'Sales analytics'),
('cx-analytics', 'Support analytics'),
('cx-analytics', 'CX analytics practice'),
('cx-analytics', 'CX voices and canon'),
('support-analytics', 'Grain'),
('support-analytics', 'Throughput, cycle time and capacity'),
('support-analytics', 'Satisfaction metrics (CSAT, NPS, CES)'),
('satisfaction-metrics', 'Survey methodology pitfalls'),
('satisfaction-metrics', 'Support analytics'),
('satisfaction-metrics', 'Voice of customer'),
('customer-success-analytics', 'Land and expand'),
('customer-success-analytics', 'Customer health scores'),
('customer-success-analytics', 'Churn and retention'),
('customer-health-scores', 'Health score as a modeled feature'),
('customer-health-scores', 'Customer success analytics'),
('customer-health-scores', 'Churn and retention'),
('churn-and-retention', 'Dunning and involuntary churn'),
('churn-and-retention', 'Revenue retention (GRR and NRR)'),
('churn-and-retention', 'Churn modeling in dbt'),
('voice-of-customer', 'The support to product feedback loop'),
('voice-of-customer', 'Satisfaction metrics (CSAT, NPS, CES)'),
('voice-of-customer', 'Survey methodology pitfalls'),
('cx-analytics-practice', 'Customer experience analytics'),
('cx-analytics-practice', 'Health score as a modeled feature'),
('health-score-as-a-modeled-feature', 'Grain'),
('health-score-as-a-modeled-feature', 'Churn modeling in dbt'),
('health-score-as-a-modeled-feature', 'Customer health scores'),
('support-to-product-feedback-loop', 'Taxonomy and ontology'),
('support-to-product-feedback-loop', 'Voice of customer'),
('support-to-product-feedback-loop', 'Customer success analytics'),
('survey-methodology-pitfalls', 'Testing & data quality'),
('survey-methodology-pitfalls', 'Satisfaction metrics (CSAT, NPS, CES)'),
('survey-methodology-pitfalls', 'Customer health scores'),
('the-cx-data-stack', 'Health score as a modeled feature'),
('the-cx-data-stack', 'CRM and warehouse sync'),
('the-cx-data-stack', 'Customer health scores'),
('churn-modeling-in-dbt', 'ML / AI integration'),
('churn-modeling-in-dbt', 'Health score as a modeled feature'),
('churn-modeling-in-dbt', 'Churn and retention'),
('finance-analytics', 'Data modeling'),
('finance-analytics', 'The SaaS metrics canon'),
('finance-analytics', 'Finance analytics practice'),
('finance-analytics', 'Finance voices and canon'),
('saas-metrics-canon', 'Grain'),
('saas-metrics-canon', 'MRR and ARR'),
('saas-metrics-canon', 'Counting & aggregation'),
('mrr-and-arr', 'Bookings, billings, revenue, cash'),
('mrr-and-arr', 'The SaaS metrics canon'),
('mrr-and-arr', 'MRR movements and the waterfall'),
('mrr-movements-and-the-waterfall', 'The MRR waterfall in dbt'),
('mrr-movements-and-the-waterfall', 'MRR and ARR'),
('mrr-movements-and-the-waterfall', 'Revenue retention (GRR and NRR)'),
('revenue-retention-grr-nrr', 'Churn and retention'),
('revenue-retention-grr-nrr', 'MRR movements and the waterfall'),
('revenue-retention-grr-nrr', 'The finance semantic layer'),
('unit-economics-cac-ltv-payback', 'Grain'),
('unit-economics-cac-ltv-payback', 'Unit economics of acquisition'),
('unit-economics-cac-ltv-payback', 'Efficiency metrics (Rule of 40, magic number, burn multiple)'),
('efficiency-metrics', 'Unit economics (CAC, LTV, payback)'),
('efficiency-metrics', 'Reconciling the metrics layer with the GL'),
('efficiency-metrics', 'The finance semantic layer'),
('revenue-recognition-asc-606', 'Time in data modeling'),
('revenue-recognition-asc-606', 'Bookings, billings, revenue, cash'),
('revenue-recognition-asc-606', 'Subscription and billing mechanics'),
('bookings-billings-revenue-cash', 'Revenue recognition and ASC 606'),
('bookings-billings-revenue-cash', 'MRR and ARR'),
('bookings-billings-revenue-cash', 'Reconciling the metrics layer with the GL'),
('subscription-and-billing-mechanics', 'Entities, instances & identifiers'),
('subscription-and-billing-mechanics', 'Payment processors and merchant of record'),
('subscription-and-billing-mechanics', 'Modeling billing data'),
('payment-processors-and-mor', 'Reconciling the metrics layer with the GL'),
('payment-processors-and-mor', 'Subscription and billing mechanics'),
('payment-processors-and-mor', 'Dunning and involuntary churn'),
('dunning-and-involuntary-churn', 'Churn and retention'),
('dunning-and-involuntary-churn', 'Subscription and billing mechanics'),
('dunning-and-involuntary-churn', 'Revenue retention (GRR and NRR)'),
('finance-analytics-practice', 'Finance analytics'),
('finance-analytics-practice', 'The finance semantic layer'),
('the-mrr-waterfall-in-dbt', 'Grain'),
('the-mrr-waterfall-in-dbt', 'Testing & data quality'),
('the-mrr-waterfall-in-dbt', 'MRR movements and the waterfall'),
('modeling-billing-data', 'Entities, instances & identifiers'),
('modeling-billing-data', 'Subscription and billing mechanics'),
('modeling-billing-data', 'The MRR waterfall in dbt'),
('single-source-of-truth-for-arr', 'Semantics & the semantic layer'),
('single-source-of-truth-for-arr', 'The finance semantic layer'),
('single-source-of-truth-for-arr', 'Reconciling the metrics layer with the GL'),
('reconciling-metrics-with-gl', 'Testing & data quality'),
('reconciling-metrics-with-gl', 'Bookings, billings, revenue, cash'),
('reconciling-metrics-with-gl', 'A single source of truth for ARR'),
('the-finance-semantic-layer', 'A single source of truth for ARR'),
('the-finance-semantic-layer', 'Semantics & the semantic layer'),
('the-finance-semantic-layer', 'Efficiency metrics (Rule of 40, magic number, burn multiple)'),
('ops-analytics', 'What ops analytics is'),
('ops-analytics', 'Operations analytics practice'),
('ops-analytics', 'Ops voices and canon'),
('what-ops-analytics-is', 'RevOps as a function'),
('what-ops-analytics-is', 'SLAs, SLOs and operational KPIs'),
('what-ops-analytics-is', 'FinOps and cloud cost'),
('slas-slos-operational-kpis', 'Support analytics'),
('slas-slos-operational-kpis', 'Counting & aggregation'),
('slas-slos-operational-kpis', 'Throughput, cycle time and capacity'),
('throughput-cycle-time-capacity', 'Grain'),
('throughput-cycle-time-capacity', 'SLAs, SLOs and operational KPIs'),
('throughput-cycle-time-capacity', 'Capacity forecasting'),
('efficiency-and-productivity', 'Time in data modeling'),
('efficiency-and-productivity', 'SaaS COGS and gross margin'),
('efficiency-and-productivity', 'Capacity forecasting'),
('saas-cogs-and-gross-margin', 'Cost attribution (showback and chargeback)'),
('saas-cogs-and-gross-margin', 'FinOps and cloud cost'),
('saas-cogs-and-gross-margin', 'Efficiency metrics (Rule of 40, magic number, burn multiple)'),
('finops-and-cloud-cost', 'Cost attribution (showback and chargeback)'),
('finops-and-cloud-cost', 'FOCUS and cloud billing exports'),
('finops-and-cloud-cost', 'SaaS COGS and gross margin'),
('cost-attribution-showback-chargeback', 'Relationships'),
('cost-attribution-showback-chargeback', 'Grain'),
('cost-attribution-showback-chargeback', 'FinOps and cloud cost'),
('cost-attribution-showback-chargeback', 'Cost as a data product'),
('cost-attribution-showback-chargeback', 'Cost attribution models in dbt'),
('cost-as-a-data-product', 'Materialization strategies'),
('cost-as-a-data-product', 'Semantics & the semantic layer'),
('cost-as-a-data-product', 'Cost attribution (showback and chargeback)'),
('ops-analytics-practice', 'Operations analytics'),
('ops-analytics-practice', 'Cost as a data product'),
('cost-attribution-models-in-dbt', 'Relationships'),
('cost-attribution-models-in-dbt', 'Testing & data quality'),
('cost-attribution-models-in-dbt', 'Cost attribution (showback and chargeback)'),
('cost-attribution-models-in-dbt', 'FOCUS and cloud billing exports'),
('focus-and-cloud-billing-exports', 'Cost attribution models in dbt'),
('focus-and-cloud-billing-exports', 'The forms of data'),
('focus-and-cloud-billing-exports', 'FinOps and cloud cost'),
('capacity-forecasting', 'Throughput, cycle time and capacity'),
('capacity-forecasting', 'Efficiency and productivity'),
('capacity-forecasting', 'Operational metrics in the semantic layer'),
('operational-metrics-in-the-semantic-layer', 'Semantics & the semantic layer'),
('operational-metrics-in-the-semantic-layer', 'Org models (hub and spoke)'),
('operational-metrics-in-the-semantic-layer', 'Cost as a data product'),
('org-models-hub-and-spoke', 'Team and ownership models'),
('org-models-hub-and-spoke', 'Operational metrics in the semantic layer'),
('org-models-hub-and-spoke', 'RevOps as a function')
) e(src_slug, tgt_title)
join pages s on s.slug = e.src_slug
join pages t on lower(t.title) = lower(e.tgt_title)
where s.id <> t.id
on conflict (source_type, source_id, target_type, target_id) do nothing;
