/**
 * Pure ERD serializers — DBML, SQL DDL, and dbt `schema.yml`. No React or DB
 * imports so they can be smoke-tested with `node --experimental-strip-types`.
 *
 * Inputs mirror `getDiagramData`: a list of models (each with ordered columns)
 * and the relationships whose endpoints are on the diagram. Column-level
 * relationships are emitted as foreign keys / refs; model-level ones (no join
 * column) degrade gracefully to comments where DDL can't express them.
 */

export type ExportCardinality = "one_to_one" | "one_to_many" | "many_to_many";

export type ExportColumn = {
  name: string;
  dataType: string | null;
  description: string | null;
  isPk: boolean;
  isFk: boolean;
  tests: string[];
};

export type ExportModel = {
  name: string;
  description?: string | null;
  columns: ExportColumn[];
};

export type ExportRelationship = {
  fromModelName: string;
  fromColumnName: string | null;
  toModelName: string;
  toColumnName: string | null;
  cardinality: ExportCardinality;
};

export type ExportInput = {
  diagramName: string;
  models: ExportModel[];
  relationships: ExportRelationship[];
};

const DEFAULT_TYPE = "text";

/* -------------------------------------------------------------------------- */
/* Helpers                                                                     */
/* -------------------------------------------------------------------------- */

/** Quote a DBML/SQL identifier only when it isn't a plain snake/word token. */
function ident(name: string): string {
  return /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name) ? name : `"${name.replace(/"/g, '""')}"`;
}

/** Only emit relationships whose both columns are known (FK-expressible). */
function columnRelationships(rels: ExportRelationship[]): ExportRelationship[] {
  return rels.filter((r) => r.fromColumnName && r.toColumnName);
}

/* -------------------------------------------------------------------------- */
/* DBML                                                                        */
/* -------------------------------------------------------------------------- */

/** DBML cardinality operator (placed between the two endpoints in a Ref). */
function dbmlOp(c: ExportCardinality): string {
  switch (c) {
    case "one_to_one":
      return "-";
    case "many_to_many":
      return "<>";
    case "one_to_many":
    default:
      return ">";
  }
}

export function toDBML(input: ExportInput): string {
  const lines: string[] = [];
  lines.push(`// ${input.diagramName} — generated by taro`);
  lines.push("");

  for (const m of input.models) {
    lines.push(`Table ${ident(m.name)} {`);
    if (m.columns.length === 0) {
      lines.push("  // (no columns)");
    }
    for (const c of m.columns) {
      const type = c.dataType?.trim() || DEFAULT_TYPE;
      const settings: string[] = [];
      if (c.isPk) settings.push("pk");
      const note = c.description?.trim();
      if (note) settings.push(`note: '${note.replace(/'/g, "\\'")}'`);
      const suffix = settings.length ? ` [${settings.join(", ")}]` : "";
      lines.push(`  ${ident(c.name)} ${type}${suffix}`);
    }
    lines.push("}");
    lines.push("");
  }

  const colRels = columnRelationships(input.relationships);
  if (colRels.length) {
    for (const r of colRels) {
      lines.push(
        `Ref: ${ident(r.fromModelName)}.${ident(r.fromColumnName!)} ${dbmlOp(
          r.cardinality,
        )} ${ident(r.toModelName)}.${ident(r.toColumnName!)}`,
      );
    }
    lines.push("");
  }

  return lines.join("\n").replace(/\n+$/, "\n");
}

/* -------------------------------------------------------------------------- */
/* SQL DDL                                                                     */
/* -------------------------------------------------------------------------- */

export function toSQL(input: ExportInput): string {
  const lines: string[] = [];
  lines.push(`-- ${input.diagramName} — generated by taro`);
  lines.push("");

  for (const m of input.models) {
    lines.push(`CREATE TABLE ${ident(m.name)} (`);
    const pkCols = m.columns.filter((c) => c.isPk).map((c) => ident(c.name));
    const body: string[] = [];
    for (const c of m.columns) {
      const type = c.dataType?.trim() || DEFAULT_TYPE;
      body.push(`  ${ident(c.name)} ${type}`);
    }
    if (pkCols.length) {
      body.push(`  PRIMARY KEY (${pkCols.join(", ")})`);
    }
    if (body.length === 0) body.push("  -- (no columns)");
    lines.push(body.join(",\n"));
    lines.push(");");
    lines.push("");
  }

  // Foreign keys for column-level relationships; comment the rest.
  for (const r of input.relationships) {
    if (r.fromColumnName && r.toColumnName) {
      lines.push(
        `ALTER TABLE ${ident(r.fromModelName)} ADD FOREIGN KEY (${ident(
          r.fromColumnName,
        )}) REFERENCES ${ident(r.toModelName)} (${ident(r.toColumnName)}); ` +
          `-- ${cardinalityLabel(r.cardinality)}`,
      );
    } else {
      lines.push(
        `-- FK ${r.fromModelName} -> ${r.toModelName} (${cardinalityLabel(
          r.cardinality,
        )}); join columns unset`,
      );
    }
  }
  if (input.relationships.length) lines.push("");

  return lines.join("\n").replace(/\n+$/, "\n");
}

function cardinalityLabel(c: ExportCardinality): string {
  switch (c) {
    case "one_to_one":
      return "1:1";
    case "many_to_many":
      return "N:N";
    case "one_to_many":
    default:
      return "1:N";
  }
}

/* -------------------------------------------------------------------------- */
/* dbt schema.yml                                                              */
/* -------------------------------------------------------------------------- */

/** Minimal YAML string escaping: quote when it could be misparsed. */
function yamlStr(value: string): string {
  if (value === "") return '""';
  if (/^[\w .\-/]+$/.test(value) && !/^[\d.]+$/.test(value)) return value;
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export function toDbtSchema(input: ExportInput): string {
  const lines: string[] = [];
  lines.push("version: 2");
  lines.push("");
  lines.push("models:");

  for (const m of input.models) {
    lines.push(`  - name: ${yamlStr(m.name)}`);
    const desc = m.description?.trim();
    if (desc) lines.push(`    description: ${yamlStr(desc)}`);
    if (m.columns.length) {
      lines.push("    columns:");
      for (const c of m.columns) {
        lines.push(`      - name: ${yamlStr(c.name)}`);
        const cdesc = c.description?.trim();
        if (cdesc) lines.push(`        description: ${yamlStr(cdesc)}`);
        // PK implies unique + not_null; merge with any inline tests.
        const tests = new Set<string>();
        if (c.isPk) {
          tests.add("unique");
          tests.add("not_null");
        }
        for (const t of c.tests) {
          const trimmed = t.trim();
          if (trimmed) tests.add(trimmed);
        }
        if (tests.size) {
          lines.push("        tests:");
          for (const t of tests) lines.push(`          - ${yamlStr(t)}`);
        }
      }
    }
  }

  return lines.join("\n") + "\n";
}

/* -------------------------------------------------------------------------- */
/* Format registry                                                             */
/* -------------------------------------------------------------------------- */

export type ErdExportFormat = "dbml" | "sql" | "dbt";

export const ERD_EXPORT_META: Record<
  ErdExportFormat,
  { label: string; ext: string; contentType: string }
> = {
  dbml: { label: "DBML", ext: "dbml", contentType: "text/plain; charset=utf-8" },
  sql: { label: "SQL DDL", ext: "sql", contentType: "text/plain; charset=utf-8" },
  dbt: { label: "dbt schema.yml", ext: "yml", contentType: "text/yaml; charset=utf-8" },
};

export function serializeErd(format: ErdExportFormat, input: ExportInput): string {
  switch (format) {
    case "dbml":
      return toDBML(input);
    case "sql":
      return toSQL(input);
    case "dbt":
      return toDbtSchema(input);
  }
}
